begin;
select plan(30);

select ok((select relrowsecurity from pg_class where oid = 'public.workspaces'::regclass), 'workspaces has RLS enabled');
select ok((select relrowsecurity from pg_class where oid = 'public.documents'::regclass), 'documents has RLS enabled');
select ok((select relrowsecurity from pg_class where oid = 'public.events'::regclass), 'events has RLS enabled');
select ok((select relrowsecurity from pg_class where oid = 'public.meetings'::regclass), 'meetings has RLS enabled');
select ok((select relrowsecurity from pg_class where oid = 'public.tasks'::regclass), 'tasks has RLS enabled');
select ok((select relrowsecurity from pg_class where oid = 'public.quick_links'::regclass), 'quick links has RLS enabled');
select ok((select relrowsecurity from pg_class where oid = 'public.audit_log'::regclass), 'audit log has RLS enabled');
select has_column('public', 'profiles', 'organization', 'profiles capture member organisations');
select has_column('public', 'profiles', 'job_title', 'profiles capture member job titles');
select is((select count(*)::integer from pg_constraint where conname = 'workspace_members_profile_fkey' and conrelid = 'public.workspace_members'::regclass and contype = 'f'), 1, 'workspace members expose their profile relationship');
select ok(has_column_privilege('authenticated', 'public.profiles', 'organization', 'UPDATE'), 'authenticated users can request organisation updates under RLS');
select is((select public.is_workspace_member(-1)), false, 'unknown workspace membership is denied');
select is((select public.is_workspace_owner(-1)), false, 'unknown workspace ownership is denied');
select has_function('public', 'bootstrap_workspace', array['text'], 'workspace bootstrap function exists');
select has_function('public', 'create_due_reminders', array[]::text[], 'reminder function exists');
select has_column('public', 'document_versions', 'storage_provider', 'document versions identify their storage provider');
select has_function('public', 'register_r2_upload', array['bigint','bigint','bigint','text','text','text','bigint'], 'R2 upload registration function exists');
select has_function('public', 'get_r2_download', array['bigint'], 'R2 download authorization function exists');
select ok((select public from storage.buckets where id = 'company-documents') = false, 'document bucket is private');
select ok(not has_table_privilege('anon', 'public.documents', 'select'), 'anonymous users cannot read documents');
select ok(not has_table_privilege('anon', 'public.tasks', 'select'), 'anonymous users cannot read tasks');
select ok(has_table_privilege('authenticated', 'public.documents', 'select'), 'authenticated role can request document reads under RLS');
select ok(has_table_privilege('authenticated', 'public.tasks', 'insert'), 'authenticated role can create content under RLS');
select ok(not has_table_privilege('authenticated', 'public.workspace_members', 'update'), 'membership changes are not exposed to browser clients');
select ok(not has_table_privilege('authenticated', 'public.audit_log', 'insert'), 'audit entries cannot be forged by browser clients');
select is((select count(*)::integer from pg_policies where schemaname = 'public' and tablename = 'documents' and cmd = 'SELECT'), 1, 'documents have an explicit member-select policy');
select is((select count(*)::integer from pg_policies where schemaname = 'public' and tablename = 'profiles' and cmd = 'UPDATE' and with_check like '%auth.uid%'), 1, 'profile updates are limited to the signed-in user');
select is((select count(*)::integer from pg_policies where schemaname = 'public' and tablename = 'audit_log' and cmd = 'SELECT' and qual like '%is_workspace_owner%'), 1, 'audit reads are owner-only');
select is((select count(*)::integer from pg_trigger where tgname = 'workspace_members_protect_final_owner' and not tgisinternal), 1, 'final-owner protection trigger is installed');
select is((select count(*)::integer from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname like 'company_documents%'), 0, 'storage objects have no direct browser policy; signed Edge Function access is required');

select * from finish();
rollback;
